### ISSUE TITLE
Narrowing conversion error seen on 32-bit architectures

### ISSUE THREAD

**Issue by afif-elghraoui** [PacificBiosciences/blasr_libcpp#108]
In Debian, we noticed build failures on 32-bit architectures due to narrowing conversion. You can see the details at <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807583>

I was able to fix the build on i386 by applying the following patch (as advised in the bug report I linked above)

```diff
--- pbseqlib.orig/alignment/tuples/TupleMask.h
+++ pbseqlib/alignment/tuples/TupleMask.h
@@ -1,10 +1,12 @@
 #ifndef TUPLES_TUPLE_MASK
 #define TUPLES_TUPLE_MASK
+
+#include <stdint.h>
 //
 // Each f is conveniently 2 bases.
 //
 //                     
-static unsigned long TupleMask[] = {0, 0xf, 0xff, 0xfff, 0xffff, 0xfffff, 0xffffff,  // 0 - 6
+static uint64_t TupleMask[] = {0, 0xf, 0xff, 0xfff, 0xffff, 0xfffff, 0xffffff,  // 0 - 6
                                   0xfffffff, 0xfffffff, 0xffffffff, 0xfffffffff,   // 7 - 9
                                   0xffffffffff, 0xfffffffffff, 0xffffffffffff,     // 10-12
                                   0xfffffffffffff, 0xffffffffffffff, 0xfffffffffffffff, // 13-15
```

I am not able to run the full test suite because I don't have all the required data files, so I wanted to bring this to your attention to make sure everything's alright.

**Comment by pb-cdunn** [comment]
Thank you! We'll definitely apply that patch.
