### ISSUE TITLE
libconfig.h not found

### ISSUE THREAD

**Issue by ink1** [PacificBiosciences/blasr_libcpp#157]
not sure whether this is related to blasr configure.py or something else. i was building blasr and the first make step "make build-submodule" could not find libconfig.h because it was expected to be local in some places:
blasr/libcpp/hdf/HDFBaseCallsWriter.cpp:#include "../pbdata/libconfig.h"
blasr/libcpp/hdf/HDFBaxWriter.cpp:#include "../pbdata/libconfig.h"
blasr/libcpp/hdf/HDFPulseCallsWriter.cpp:#include "../pbdata/libconfig.h"
blasr/libcpp/hdf/HDFPulseWriter.cpp:#include "../pbdata/libconfig.h"
blasr/libcpp/hdf/HDFZMWWriter.cpp:#include "../pbdata/libconfig.h"

Should it be this?
#include <libconfig.h>

But as a quick fix it's easier to just copy libconfig.h to pbdata/

**Comment by ylipacbio** [comment]
Please install blasr via pitchfork `https://github.com/PacificBiosciences/pitchfork`. It is convenient, easy to use and is the recommended way of installing blasr.
