### ISSUE TITLE
blasr with BAM support fails due to blasr_libcpp related problem

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/blasr_libcpp#162]
Hi
I installed the version 5.3 of blasr without BAM support  which worked flawless for the *.bas files.
Now I wanted to add BAM support in order to be ready for sequel data and run into problems.

Essentially I ran for building:

<pre><code>
LIBCPP=/software/Development/Libraries/blasr_libcpp/20170117
PBBAM=/software/Development/Libraries/pbbam/0.7.4
HTS=/software/UHTS/Analysis/HTSlib_PB/170119

export LD_RUN_PATH=$LIBCPP/hdf:$LIBCPP/pbdata:$LIBCPP/alignment:$HTS/lib

export HDF5_INC=/software/include
export HDF5_LIB=/software/lib
export LIBPBIHDF_INC=$LIBCPP/hdf
export LIBPBDATA_INC=$LIBCPP/pbdata
export LIBPBDATA_LIB=$LIBCPP/pbdata
export LIBBLASR_INC=$LIBCPP/alignment
export LIBBLASR_LIB=$LIBCPP/alignment 
export LIBPBIHDF_LIB=$LIBCPP/hdf 

export PPBAM_ROOTDIR=$PBBAM
export PBBAM_INC=$PBBAM/include
export PBBAM_LIB=$PBBAM/lib64
export HTSLIB_INC=$HTS/include
export HTSLIB_LIB=$HTS/lib
export SH_LIB_EXT=".a"

./configure.py CXXFLAGS=-O3 --shared  

#build blasr
make --debug=b -j4 all 
</code></pre>

This seems to compiles fine and blasr works for *.bas files. If I use a PacBio bam file though as reads if fails:

<pre><code>
[INFO] 2017-01-26T15:12:46 [blasr] started.
ERROR! Hit unreachable code in files/ReaderAgglomerate.cpp:293
blasr: files/ReaderAgglomerate.cpp:293: int ReaderAgglomerate::Initialize(bool): Assertion `0' failed.
Aborted
</code></pre>

Checking where this comes from it is located in my blasr_licpp folder.
The blasr_libcpp installation was done as described:

<pre><code>
PBBAM=/software/Development/Libraries/pbbam/0.7.4
HTS=/software/UHTS/Analysis/HTSlib_PB/170119

export LD_RUN_PATH=$HTS/lib
export PPBAM_ROOTDIR=$PBBAM
export PBBAM_INC=$PBBAM/include
export PBBAM_LIB=$PBBAM/lib64
export HTSLIB_INC=$HTS/include
export HTSLIB_LIB=$HTS/lib
# Put the PATH to our tools first
#NOPBBAM=1 ./configure.py HDF5_INC=/software/include/ HDF5_LIB=/software/lib/ 
#trying to activate PBBAM as switching for SEQUEL
NOPBBAM=0 ./configure.py HDF5_INC=/software/include/ HDF5_LIB=/software/lib/  
make -j all
</code></pre>

The compilation of blasr_libcpp succeeded successful as well, but now looking again at the logs with the blasr error in mind I found actually a warning during the blasr_libcpp compilation:

<pre><code>
files/ReaderAgglomerate.cpp:203:40: warning: unused parameter 'unrolled_mode' [-Wunused-parameter]
 int ReaderAgglomerate::Initialize(bool unrolled_mode) {
                                        ^
files/ReaderAgglomerate.cpp:203:40: warning: unused parameter 'unrolled_mode' [-Wunused-parameter]
 int ReaderAgglomerate::Initialize(bool unrolled_mode) {
</code></pre>

Which is my only warning but makes sense now why blasr fails. Can you help me with this one, please ?

**Comment by ylipacbio** [comment]
Hi ebioman,

It seems like pbbam is not compiled with blasr_libcpp.

Since BLASR can build with cmake now, it might be easier to build BLASR using cmake [(instructions)](https://github.com/PacificBiosciences/blasr/blob/master/doc/INSTALL_CMAKE.md).

Or you can manually reconfig libcpp and recompile blasr.
```
cd libcpp
# reconfig libcpp
echo '#define USE_PBBAM" > pbdata/libconfig.h
make clean && make -j 8 # rebuild libcpp
cd .. && make clean && make blasr # rebuild blasr
```

**Comment by ebioman** [comment]
Hello @ylipacbio 
Thanks for pointing out the very recent update for CMAKE. Unfortunately I am still on CentOS 6 with cmake V3.2 and we wont see any upgrade there until we upgrade to CentOS 7.

So I went for alternative which you proposed and added the `#define USE_PBBAM` to the `blasr_lipbpp/pbdata/libconfig.h`. I compiled this which went through without a hick-up.

Then I compiled blasr again, again nothing unexpected.
**But** upon execution of blasr I get the following error now:
  
    blasr: symbol lookup error: /software/Development/Libraries/blasr_libcpp/20170117/alignment/libblasr.so: undefined symbol: _ZTIN6PacBio3BAM9BamRecordE

Which is as well the case for the utils. So it screwed up my libblasr.so for good.
I was worried that my pbbam installation was the source of all devil here but the cmake test went through without problems. So it seems that blasr_libcpp does not compile correctly.

What I found a little bit confusing was that `pbdata/libconfig.h` contains only one line, the  `#define USE_PBBAM` line. Is that actually normal ?

**Comment by ylipacbio** [comment]
It's normal to see just one line in libcofig.h. 

MJ will provide a solution for the linking error that you saw.

**Comment by mhsieh** [comment]
Regarding this:
```
blasr: symbol lookup error: /software/Development/Libraries/blasr_libcpp/20170117/alignment/libblasr.so: undefined symbol: _ZTIN6PacBio3BAM9BamRecordE
```
Is `/software/Development/Libraries/pbbam/0.7.4/lib64` in your LD_LIBRARY_PATH environment variable?

**Comment by ebioman** [comment]
Hello @mhsieh 
It is during run-time - but maybe it is not correctly during compilation time. I will have to investigate this.
The problem is that I am making RPM packages for which I have to do the following in order to have blasr with bam support:

 - compile HTSlib fork from PacBio
 - compile pbbam with the above lib
 - compile blasr_libcpp with the 2 above
 - finally compile blasr with all the 3 above

As the exported variables have to be set correctly it might be possible that this is not present.
But during compilation it should fail and adding it afterwards manually to the LD_LIBRARY_PATH does not rescue it neither.
Strange..

**Comment by ebioman** [comment]
Hi
So I believe I found the problem. I defined the variables for pbbam wrongly 
It should have been in the spec file:

    setenv			PBBAM_LIB    		%{_libdir}
    setenv			PBBAM_INC		    %{_includedir}


Now everything is fine. Thanks again for pointing me in the correct direction.
