### ISSUE TITLE
Build issue: no known conversion for argument 1 from ‘H5::H5File’ to ‘H5::Group&’

### ISSUE THREAD

**Issue by tillea** [PacificBiosciences/blasr_libcpp#166]
Hi,
when trying to build the version 5.3.1 release I get

    c++ -Iblasr@sha -I. -I.. -I../ -I/usr/include/hdf5/serial -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++11 -g -O2 -fdebug-prefix-map=/build/libblasr-5.3.1=. -fstack-protector-strong -      Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wno-delete-non-virtual-dtor -Wno-unused-variable -Wno-non-virtual-dtor  -MD -MQ 'blasr@sha/hdf_HDFAtom.cpp.o' -MF 'blasr@sha/hdf_HDFAtom.   cpp.o.d' -o 'blasr@sha/hdf_HDFAtom.cpp.o' -c ../hdf/HDFAtom.cpp
    In file included from ../hdf/HDFAtom.cpp:1:
    ../hdf/HDFAtom.hpp: In member function ‘int HDFAtom<T>::Initialize(H5::H5File&, const string&, const string&)’:
    ../hdf/HDFAtom.hpp:64:44: error: no matching function for call to ‘HDFGroup::Initialize(H5::H5File&, const string&)’
             group.Initialize(hdfFile, groupName);
                                                ^
    In file included from ../hdf/HDFData.hpp:10,
                     from ../hdf/HDFAtom.hpp:12,
                     from ../hdf/HDFAtom.cpp:1:
    ../hdf/HDFGroup.hpp:28:9: note: candidate: ‘int HDFGroup::Initialize(H5::Group&, std::__cxx11::string)’
         int Initialize(H5::Group& fg, std::string groupName);
             ^~~~~~~~~~
    ../hdf/HDFGroup.hpp:28:9: note:   no known conversion for argument 1 from ‘H5::H5File’ to ‘H5::Group&’
    ../hdf/HDFGroup.hpp:30:9: note: candidate: ‘int HDFGroup::Initialize(HDFGroup&, std::__cxx11::string)’
         int Initialize(HDFGroup& parentGroup, std::string groupName);
             ^~~~~~~~~~
    ../hdf/HDFGroup.hpp:30:9: note:   no known conversion for argument 1 from ‘H5::H5File’ to ‘HDFGroup&’

I was discussing this on the Debian Med developers list (since I intend to package this lib for Debian) and there was [one answer](https://alioth-lists.debian.net/pipermail/debian-med-packaging/2018-September/065508.html) giving reasons why this can not work.
Do you have any hint how I can build blasr_libcpp with recent hdf5?

**Comment by armintoepfer** [comment]
We don't support source builds. Please install blasr via bioconda as the README states. Thank you.
