### ISSUE TITLE
Set the SM Tag in the RG Group of the Header

### ISSUE THREAD

**Issue by cancan101** [PacificBiosciences/blasr_libcpp#33]
It does [not appear that the SM tag is being set](https://github.com/PacificBiosciences/blasr_libcpp/blob/49c3dda0a0b8d2c7916a026ae12f49d0682649b8/alignment/format/SAMHeaderPrinter.cpp#L327-L331) in the [RG group](https://samtools.github.io/hts-specs/SAMv1.pdf). This tag is required by down stream systems like Picard and GATK.

**Comment by ylipacbio** [comment]
Hi cancan101,

This has been opened as an issue under pacbio fileformats.

https://github.com/PacificBiosciences/PacBioFileFormats/issues/1

Thank you for reporting it!
