### ISSUE TITLE
Separate blasr and blasr_libcpp?

### ISSUE THREAD

**Issue by outpaddling** [PacificBiosciences/blasr_libcpp#37]
Quick question:

Since blasr_libcpp is a separate project, I'm inclined to package it separately from blasr.

However, the blasr install instructions focus on building it as a submodule from within the blasr directory, and there is no install target in the blasr_libcpp makefile.

So:

1) Do any programs outside blasr depend on blasr_libcpp?

2) If so, what in blasr_libcpp should be installed?  Obviously it would include all the libraries and at least some of the header files, but which ones?

Thanks,

    Jason

**Comment by pb-cdunn** [comment]
1. Yes. E.g. **pbdagcon**.
1. That's a fair question. I've created a separate issue for *install* targets, #38.

**Comment by outpaddling** [comment]
Thanks much.  The ability to deploy shared libraries via a package manager and share them among other packages would be very helpful to us.  We support research computing across a large campus and have to deploy hundreds of packages on our clusters and development servers.  Without a unified deployment method, we wouldn't be able to manage it all...
