### ISSUE TITLE
Can't build blasr_libcpp locally on Fedora

### ISSUE THREAD

**Issue by bnbowman** [PacificBiosciences/blasr_libcpp#40]
It looks like the project isn't completely independent of PBBam:
```
g++ -std=c++11 -pedantic -MMD -MP   -I/home/bbowman/git/blasr_libcpp -I/home/bbowman/git/blasr_libcpp/pbdata/ -Imatrix -Ireads -Iqvs -Imetagenome -Isaf -Iutils -I../alignment -MF"FASTQReader.d" -MT"FASTQReader.o FASTQReader.d" -c FASTQReader.cpp -o FASTQReader.o
In file included from FASTASequence.hpp:13:0,
                 from FASTQReader.hpp:4,
                 from FASTQReader.cpp:4:
DNASequence.hpp:14:29: fatal error: pbbam/BamRecord.h: No such file or directory
 #include "pbbam/BamRecord.h"
                             ^
```

PbBam on the other hand builds locally just fine - how do I point blasr_libcpp to those files?

**Comment by pb-cdunn** [comment]
Use `configure.py`. You can specify the PBBAM_INC and _LIB dirs. See also:
* https://github.com/PacificBiosciences/pith/blob/master/sh/mobs/pacbio/libblasr/buildctl.sh#L83

Or run 'mobs -b libblasr' and look at the command-line for configure.py.

**Comment by bnbowman** [comment]
Then could we please get an update to the README to reflect those dependencies?

And for those of us on the science side of the team, how do I get access to mobs?

**Comment by pb-cdunn** [comment]
Ok. Opened #42.

> how do I get access to mobs?

    //depot/software/smrtanalysis/build/*/mobs -h

Or write to Herb Maeder. But mobs is only for use within our Perforce tree.

**Comment by pb-cdunn** [comment]
In your Fedora build, where are pbbam, hdf5, htslib, and boost? Are they all in something like `/usr/include` and `/usr/lib`?

**Comment by pb-cdunn** [comment]
@bnbowman, I need a response on this. I need to know how different people install on different systems. I can make it almost trivial, but only if you work with me. Skype sometime?

**Comment by pb-cdunn** [comment]
Ok. This should be much easier to use now.

    PREFIX=/usr/local ./configure.py

Or wherever you install things. You can still override specific packages.
