### ISSUE TITLE
SAMHeaderPrinter.cpp produces non-spec conformant SAM header

### ISSUE THREAD

**Issue by kortschak** [PacificBiosciences/blasr_libcpp#97]
The SAM spec allows three fields in the `@HD` line: `VN` (required), `SO` and `GO`. SAMHeaderPrinter.cpp adds `pb` - which apart from being present at all (it should not be) is not in `@[A-Z][A-Z]`. This breaks spec-conformant parsers. 

Really that information should be in a `@PG` line.

**Comment by ylipacbio** [comment]
Hi kortschak,

Thanks for bringing this up. 

First, BAM file produced by BLASR should all conform to the PacBio BAM specification described at
https://github.com/PacificBiosciences/PacBioFileFormats/blob/3.0/BAM.rst

Second, ```@HD VN:xxx SO:xxx pb:xxx ``` should conform to SAM sepc. 
```
Each header line begins with the character ‘@’ followed by one of the two-letter header record type codes defined in this section. In the header, each line is TAB-delimited and, apart from @CO lines, each data field follows a format ‘TAG:VALUE’ where TAG is a two-character string that defines the format and content of VALUE. Thus header lines match /^@[A-Z][A-Z](\t[A-Za-z][A-Za-z0-9]:[ -~]+)+$/
```

Sincerely,
Yuan

**Comment by kortschak** [comment]
It may conform to the PB BAM spec, but it most certainly does not conform to the SAM spec. Please not the table on page 3 of the spec that lists record types that may be include for each header line type. @HD includes 3. Note that in no place is the header record set described as being extensible.

This should not be closed.

**Comment by kortschak** [comment]
I've had another look at this, and while you're correct about the pb:VALUE  tag, SO:UNKNOWN is written in upper case while all the valid values for SO are lc (this is also true for GO). In tolerant parsers this is not a problem since a failed parse of that value is like to result in the default ("unknown") which is what you want. However, strict parsers will reject this line.
